Repository trufflesuite/truffle, pull requests merged in 2022-09, with the labels that each got.

#5508 Use canonical URL for goerli-optimistic
  packages/source-fetcher/lib/etherscan.ts
  packages/source-fetcher/lib/networks.ts
Labels: internal improvement

#5512 Fix computation of event status in flattedEvents
  packages/debugger/lib/txlog/selectors/index.js
Labels: 🐜 bug fix

#5519 Add step information to txlog
  packages/debugger/lib/txlog/actions/index.js
  packages/debugger/lib/txlog/reducers.js
  packages/debugger/lib/txlog/sagas/index.js
  packages/debugger/lib/txlog/selectors/index.js
  packages/debugger/test/txlog.js
Labels: enhancement

#5540 Eliminate circular dependency between compile-solidity and resolver
  packages/compile-solidity/package.json
Labels: internal improvement

#5546 Increase timeout on cyclic dependencies test
  packages/truffle/test/scenarios/cyclic_dependencies/compiles.js
Labels: internal improvement

#5557 Type opcodes table as const in @truffle/code-utils
  packages/code-utils/src/index.ts
  packages/code-utils/src/opcodes.ts
  packages/code-utils/src/types.ts
  packages/code-utils/test/opcodes.test.ts
Labels: internal improvement, breaking-change: @truffle/code-utils

#5570 Add new Sourcify networks for late September
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#5561 Add raw storage writes to txlog
  packages/debugger/lib/txlog/actions/index.js
  packages/debugger/lib/txlog/reducers.js
  packages/debugger/lib/txlog/sagas/index.js
  packages/debugger/lib/txlog/selectors/index.js
  packages/debugger/test/txlog.js
Labels: enhancement
