Repository trufflesuite/truffle, pull requests merged in 2022-11, with the labels that each got.

#5665 Remove ethpm-v1 concerns
  packages/compile-solidity-tests/test/parser.ts
  packages/compile-solidity-tests/test/sources/v0.4.15/MyContract.sol
  packages/config/src/configDefaults.ts
  packages/resolver/lib/resolver.ts
  packages/resolver/lib/sources/ethpm-v1.ts
  packages/resolver/lib/sources/index.ts
  packages/truffle/test/scenarios/resolver/resolver.js
  packages/truffle/test/sources/monorepo/installed_contracts/ethpmpkg/EthPMImport.sol
  packages/truffle/test/sources/monorepo/truffleproject/contracts/Importer.sol
Labels: internal improvement

#5669 Update apollo-server to ^3.11.0
  packages/db/package.json
  yarn.lock
Labels: dependencies

#5678 Add .prettierignore
  .prettierignore
Labels: internal improvement

#5683 Update babel-loader to 9.1.0
  packages/debugger/package.json
  yarn.lock
Labels: dependencies

#5693 Remove babel from debugger
  packages/debugger/package.json
  packages/debugger/webpack/webpack.config-common.js
  packages/debugger/webpack/webpack.config-test.js
  yarn.lock
Labels: internal improvement

#5694 Fix error message on hitting `v` in debugger with no tx loaded
  packages/core/lib/debug/printer.js
  packages/debugger/lib/data/selectors/index.js
Labels: 🐜 bug fix

#5646 Allow adding compilations to an existing `ProjectDecoder`
  packages/codec/lib/compilations/utils.ts
  packages/codec/lib/errors.ts
  packages/codec/lib/index.ts
  packages/decoder/lib/decoders.ts
  packages/decoder/test/current/test/additional-test.js
  packages/encoder/lib/encoders.ts
Labels: enhancement, new-feature: @truffle/decoder

#5700 CI: shorten prefix for debug logging
  packages/truffle/test/scenarios/commandRunner.js
Labels: internal improvement

#5708 Early return dashboard event handlers if network isn't dashboard
  packages/events/defaultSubscribers/dashboard.js
Labels: internal improvement, dashboard

#5621 Decode requests in dashboard
  packages/dashboard-message-bus-client/lib/client.ts
  packages/dashboard-message-bus-common/lib/messages.ts
  packages/dashboard/dev-server/all.ts
  packages/dashboard/dev-server/dashboard.ts
  packages/dashboard/dev-server/webpack.ts
  packages/dashboard/lib/DashboardServer.ts
  packages/dashboard/package.json
  packages/dashboard/public/index.html
  packages/dashboard/public/logo192.png
  packages/dashboard/public/logo512.png
  packages/dashboard/public/manifest.json
  packages/dashboard/public/robots.txt
  packages/dashboard/src/App.tsx
  packages/dashboard/src/components/MantineGlobal.tsx
  packages/dashboard/src/components/composed/Palette.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/Details/Expanded.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/Details/Expanded/DecodedParams.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/Details/Expanded/RawParams.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/Details/Expanded/index.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/Details/index.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/Overview.tsx
  packages/dashboard/src/components/composed/RPCs/RPC/index.tsx
  packages/dashboard/src/contexts/DashContext/DashContext.ts
  packages/dashboard/src/contexts/DashContext/DashProvider.tsx
  packages/dashboard/src/contexts/DashContext/state.ts
  packages/dashboard/src/contexts/DashContext/types/Action.ts
  packages/dashboard/src/contexts/DashContext/types/Schema.ts
  packages/dashboard/src/contexts/DashContext/types/State.ts
  packages/dashboard/src/contexts/DashContext/types/index.ts
  packages/dashboard/src/index.tsx
  packages/dashboard/src/types/assets.d.ts
  packages/dashboard/src/types/react-app-env.d.ts
  packages/dashboard/src/utils/constants.ts
  packages/dashboard/src/utils/dash.ts
  packages/dashboard/src/utils/notifications/decode.tsx
  packages/dashboard/src/utils/notifications/index.ts
  packages/dashboard/src/window.d.ts
  packages/dashboard/tsconfig.json
  packages/dashboard/webpack.config.ts
  packages/events/defaultSubscribers/dashboard.js
  packages/workflow-compile/src/index.ts
  yarn.lock
Labels: dashboard, new-feature: @truffle/dashboard

#5717 Remove custom jest resolver for db
  packages/db/package.json
  packages/db/test/jest-resolver.js
Labels: db, internal improvement

#5727 Update Sourcify networks for late November 2022
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#5740 dashboard: Fix decoding text overflow
  packages/dashboard/src/components/composed/RPCs/RPC/Overview.tsx
Labels: dashboard
