Repository trufflesuite/truffle, pull requests merged in 2022-12, with the labels that each got.

#5777 Add `encodeCreation()` method to Encoder
  packages/encoder/lib/encoders.ts
  packages/encoder/test/constructor.test.ts
Labels: enhancement, new-feature: @truffle/encoder

#5763 Include a reverse registrar when deploying a dev registry
  packages/deployer/builtContracts/ENSRegistry.json
  packages/deployer/builtContracts/PublicResolver.json
  packages/deployer/builtContracts/ReverseRegistrar.json
  packages/deployer/ens.js
  packages/deployer/test/ens.js
Labels: enhancement

#5782 Fix missing mocha runner during in-test debugging setup
  packages/core/lib/debug/mocha.js
  packages/test/src/Test.ts
Labels: 🐜 bug fix

#5780 remove `require` cache invalidation
  packages/config/package.json
  packages/config/src/index.ts
  packages/core/test/lib/commands/config.js
Labels: breaking-change: @truffle/config

#5743 Make @truffle/provider compatible with EIP-1193
  packages/provider/wrapper.js
Labels: internal improvement

#5797 Bump minimum Node version check to 14
  packages/core/cli.js
Labels: internal improvement
