Repository trufflesuite/truffle, pull requests merged in 2022-03, with the labels that each got.

#4693 Dependency update: Bump ganache to ^7.0.3
  packages/artifactor/package.json
  packages/contract-tests/package.json
  packages/core/package.json
  packages/db/package.json
  packages/debugger/package.json
  packages/decoder/package.json
  packages/deployer/package.json
  packages/environment/package.json
  packages/hdwallet-provider/package.json
  packages/interface-adapter/package.json
  packages/provider/package.json
  packages/truffle/package.json
  yarn.lock
Labels: dependencies, internal improvement

#4811 Internal improvement: Remove compatibility selectors from debugger (breaking change)
  packages/debugger/lib/debugger.js
  packages/debugger/lib/session/index.js
Labels: breaking-change: @truffle/debugger

#4919 Run CI for PRs targeting `feature/dashboard`
  .github/workflows/nodejs.yml
Labels: internal improvement
