Repository trufflesuite/truffle, pull requests merged in 2022-10, with the labels that each got.

#5481 Internal improvement: Update @truffle/migrate to TypeScript
  packages/box/box.ts
  packages/box/lib/utils/unbox.ts
  packages/box/package.json
  packages/core/lib/commands/migrate/prepareConfigForRealMigrations.js
  packages/core/lib/commands/migrate/runMigrations.js
  packages/core/lib/testing/Test.js
  packages/core/lib/testing/TestRunner.js
  packages/core/test/migrate.js
  packages/db/bin/codegen.js
  packages/db/package.json
  packages/db/tsconfig.json
  packages/db/typings/.gitkeep
  packages/db/typings/schema.d.ts
  packages/decoder/test/helpers.js
  packages/interface-adapter/lib/index.ts
  packages/migrate/.gitignore
  packages/migrate/emitEvent.js
  packages/migrate/package.json
  packages/migrate/src/Migration.ts
  packages/migrate/src/ResolverIntercept.ts
  packages/migrate/src/emitEvent.ts
  packages/migrate/src/index.ts
  packages/migrate/test/index.ts
  packages/migrate/test/migration.ts
  packages/migrate/tsconfig.json
  packages/migrate/typings/Deployer.d.ts
  packages/require/lib/types.ts
  packages/truffle/test/scenarios/commands/migrate.js
  yarn.lock
Labels: breaking-change: @truffle/migrate

#5543 Add Node v18 support and drop Node v12
  .github/workflows/nodejs.yml
  packages/core/lib/commands/init/initSource/truffle-config.js
  packages/core/lib/mnemonics/mnemonic.js
  packages/core/package.json
  packages/db/ARCHITECTURE.md
  packages/db/package.json
  packages/db/src/meta/pouch/adapters/index.ts
  packages/db/src/meta/pouch/adapters/indexeddb.ts
  packages/db/src/network/index.ts
  packages/db/src/system.ts
  packages/db/src/test/persistence.spec.ts
  packages/db/src/test/utils.ts
  packages/hdwallet-provider/package.json
  packages/hdwallet-provider/src/index.ts
  packages/hdwallet/.eslintrc.json
  packages/hdwallet/.gitignore
  packages/hdwallet/README.md
  packages/hdwallet/package.json
  packages/hdwallet/src/index.ts
  packages/hdwallet/test/hdwallet.test.ts
  packages/hdwallet/tsconfig.json
  yarn.lock
Labels: breaking-change: @truffle/db

#5597 hdwallet-provider: restrict access to internal fields
  packages/hdwallet-provider/src/index.ts
Labels: breaking-change: @truffle/hdwallet-provider

#5507 Upgrade jest to v29
  packages/abi-utils/package.json
  packages/dashboard-message-bus-e2e-test/package.json
  packages/db-kit/package.json
  packages/db/package.json
  packages/encoder/package.json
  packages/from-hardhat/package.json
  packages/plugins/package.json
  packages/preserve/package.json
  packages/promise-tracker/package.json
  yarn.lock
Labels: dependencies

#5609 Add a check to help prevent generated files being checked into source control
  .github/workflows/nodejs.yml
Labels: internal improvement

#5613 Update webpack-bundle-analyzer to ^4.6.1
  packages/truffle/package.json
  yarn.lock
Labels: dependencies

#5607 Enable lerna `rejectCycles` to Truffle build
  lerna.json
  package.json
  yarn.lock
Labels: dependencies, internal improvement

#5624 Turn on strict null checks in compile-common
  packages/compile-common/src/shims/LegacyToNew.ts
  packages/compile-common/tsconfig.json
Labels: internal improvement

#5625 Add POA Core to sourcify fetcher
  packages/source-fetcher/lib/etherscan.ts
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#5631 Remove redundant scripts and ts-node-dev dependency
  packages/db/bin/server.js
  packages/db/package.json
  packages/db/test/truffle-projects/drizzle-box/.eslintrc.json
  packages/db/test/truffle-projects/drizzle-box/.gitignore
  packages/db/test/truffle-projects/drizzle-box/Readme.md
  packages/db/test/truffle-projects/drizzle-box/contracts/ComplexStorage.sol
  packages/db/test/truffle-projects/drizzle-box/contracts/Migrations.sol
  packages/db/test/truffle-projects/drizzle-box/contracts/SimpleStorage.sol
  packages/db/test/truffle-projects/drizzle-box/contracts/TutorialToken.sol
  packages/db/test/truffle-projects/drizzle-box/migrations/1_initial_migration.js
  packages/db/test/truffle-projects/drizzle-box/migrations/2_deploy_contracts.js
  packages/db/test/truffle-projects/drizzle-box/package.json
  packages/db/test/truffle-projects/drizzle-box/test/TestSimpleStorage.sol
  packages/db/test/truffle-projects/drizzle-box/test/simplestorage.js
  packages/db/test/truffle-projects/drizzle-box/truffle-config.js
  packages/db/test/truffle-projects/drizzle-box/yarn.lock
  yarn.lock
Labels: internal improvement

#5633 Increase timeout on docker tags test
  packages/core/test/lib/commands/compile.js
Labels: internal improvement

#5634 Further increase timeout on docker tag test
  packages/core/test/lib/commands/compile.js
Labels: internal improvement

#5636 Bump ts-jest from v28.0.7 to v29.0.3
  packages/abi-utils/package.json
  packages/dashboard-message-bus-e2e-test/package.json
  packages/dashboard/package.json
  packages/db-kit/package.json
  packages/db/package.json
  packages/encoder/package.json
  packages/plugins/package.json
  packages/preserve/package.json
  packages/promise-tracker/package.json
  yarn.lock
Labels: dependencies

#5637 update gh-actions to use node 16
  .github/workflows/nodejs.yml
  packages/core/test/lib/commands/compile.js
Labels: internal improvement

#5655 Update ganache to 7.5.0
  packages/artifactor/package.json
  packages/contract-tests/package.json
  packages/core/package.json
  packages/db/package.json
  packages/debugger/package.json
  packages/decoder/package.json
  packages/deployer/package.json
  packages/encoder/package.json
  packages/environment/package.json
  packages/hdwallet-provider/package.json
  packages/interface-adapter/package.json
  packages/provider/package.json
  packages/truffle/package.json
  yarn.lock
Labels: dependencies

#5651 Add event log to debugger CLI
  packages/core/lib/debug/interpreter.js
  packages/core/lib/debug/printer.js
  packages/debug-utils/index.js
Labels: enhancement, doc-change-required

#5656 Add icon for sepolia testnet to dashboard
  packages/dashboard/src/assets/icons/sepolia.png
  packages/dashboard/src/components/common/ChainIcon.tsx
Labels: dashboard
