Repository trufflesuite/truffle, pull requests merged in 2022-02, with the labels that each got.

#4436 Internal improvement: Remove reporters
  packages/config/package.json
  packages/config/src/configDefaults.ts
  packages/config/src/index.ts
  packages/core/lib/commands/migrate/run.js
  packages/core/lib/testing/SolidityTest.js
  packages/core/lib/testing/TestRunner.js
  packages/core/package.json
  packages/deployer/.gitignore
  packages/deployer/index.js
  packages/deployer/package.json
  packages/deployer/src/actions/new.js
  packages/deployer/src/deployment.js
  packages/deployer/src/linker.js
  packages/deployer/src/sanitizeMessage.js
  packages/deployer/test/await.js
  packages/deployer/test/deployer.js
  packages/deployer/test/errors.js
  packages/deployer/test/helpers/eventSystem.js
  packages/events/EventManager.js
  packages/events/Subscriber/index.js
  packages/events/SubscriberAggregator.js
  packages/events/defaultSubscribers/index.js
  packages/events/defaultSubscribers/migrate/Messages.js
  packages/events/defaultSubscribers/migrate/Reporter.js
  packages/events/defaultSubscribers/migrate/indentedSpinner.js
  packages/events/defaultSubscribers/migrate/index.js
  packages/events/package.json
  packages/migrate/Migration.js
  packages/migrate/emitEvent.js
  packages/migrate/index.js
  packages/migrate/package.json
  packages/migrate/test/index.js
  packages/migrate/test/migration.js
  packages/reporters/LICENSE
  packages/reporters/index.js
  packages/reporters/package.json
  packages/truffle/test/scenarios/commandRunner.js
  packages/truffle/test/scenarios/commands/develop.js
  packages/truffle/test/scenarios/commands/help.js
  packages/truffle/test/scenarios/migrations/describe-json.js
  packages/truffle/test/scenarios/migrations/dryrun.js
  packages/truffle/test/scenarios/migrations/errors.js
  packages/truffle/test/scenarios/stacktracing/stacktrace.js
  yarn.lock
Labels: breaking-change: @truffle/deployer, breaking-change: @truffle/events, breaking-change: @truffle/migrate

#4748 Prepare @truffle/dashboard* packages for release
  packages/core/package.json
  packages/dashboard-message-bus/package.json
  packages/dashboard-provider/package.json
  packages/dashboard/package.json
Labels: internal improvement

#4759 Remove junk from migration output
  packages/events/defaultSubscribers/compile.js
  packages/events/defaultSubscribers/migrate/Reporter.js
  packages/events/defaultSubscribers/migrate/index.js
Labels: 🐜 bug fix
