Repository trufflesuite/truffle, pull requests merged in 2023-04, with the labels that each got.

#5986 Add support for Polygon ZkEVM to Etherscan fetcher
  packages/source-fetcher/lib/etherscan.ts
  packages/source-fetcher/lib/networks.ts
Labels: enhancement

#5982 Make @truffle/dashboard-hardhat-plugin automatically manage the Dashboard Hardhat network configuration (while still allowing customization)
  packages/dashboard-hardhat-plugin/README.md
  packages/dashboard-hardhat-plugin/package.json
  packages/dashboard-hardhat-plugin/src/index.ts
  packages/dashboard-hardhat-plugin/src/type-extensions.ts
  packages/dashboard-hardhat-plugin/tsconfig.json
Labels: enhancement, doc-change-required, breaking-change: @truffle/dashboard-hardhat-plugin

#5990 Remove clover support from etherscan fetcher
  packages/source-fetcher/lib/etherscan.ts
  packages/source-fetcher/lib/networks.ts
Labels: internal improvement

#5992 Update Ganache to 7.8.0
  packages/artifactor/package.json
  packages/contract-tests/package.json
  packages/core/package.json
  packages/db/package.json
  packages/debugger/package.json
  packages/decoder/package.json
  packages/deployer/package.json
  packages/encoder/package.json
  packages/environment/package.json
  packages/hdwallet-provider/package.json
  packages/interface-adapter/package.json
  packages/provider/package.json
  packages/truffle/package.json
  yarn.lock
Labels: dependencies

#6005 Consistify location of user ENS registry address setting
  packages/config/src/configDefaults.ts
  packages/contract/lib/utils/ens.js
  packages/deployer/index.js
  packages/deployer/test/ens.js
  packages/provisioner/src/index.ts
Labels: doc-change-required, new-feature: @truffle/config
