Repository trufflesuite/truffle, pull requests merged in 2023-05, with the labels that each got.

#6014 Add compatibility flag to ResultInspector for when Maps can't be inspected
  packages/codec/lib/export.ts
  packages/codec/lib/format/utils/inspect.ts
  packages/dashboard/src/components/composed/Debugger/Variables.tsx
Labels: enhancement

#6021 Fix incorrect check for panic
  packages/core/lib/debug/printer.js
Labels: 🐜 bug fix

#5647 Implement new `truffle call` command using @truffle/encoder and @truffle/decoder
  packages/core/lib/commands/call/index.js
  packages/core/lib/commands/call/meta.js
  packages/core/lib/commands/call/run.js
  packages/core/lib/commands/commands.js
  packages/core/lib/commands/index.js
  packages/encoder/lib/adapter.ts
  packages/encoder/lib/index.ts
  packages/provider/index.js
  packages/provider/wrapper.js
  packages/truffle/test/scenarios/commands/call.js
  packages/truffle/test/sources/call/contracts/Sample.sol
  packages/truffle/test/sources/call/migrations/2_deploy_contracts.js
  packages/truffle/test/sources/call/truffle-config.js
Labels: new feature, doc-change-required

#6027 Add new chains for Sourcify for May 2023
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#6034 Change default registry in config from null to undefined
  packages/config/src/configDefaults.ts
Labels: Debugger, 🐜 bug fix

#6043 Use StringValueInfoToStringLossy function in debugger
  packages/debugger/lib/stacktrace/selectors/index.js
Labels: internal improvement

#6053 Remove ropsten, kovan, rinkeby support from Etherscan fetcher
  packages/source-fetcher/lib/etherscan.ts
Labels: internal improvement

#6052 Add `parseSignature` functions to ABI utils
  packages/abi-utils/README.md
  packages/abi-utils/lib/index.ts
  packages/abi-utils/lib/parse.test.ts
  packages/abi-utils/lib/parse.ts
  packages/abi-utils/lib/signature.test.ts
Labels: enhancement, new-feature: @truffle/abi-utils

#6055 Increase time on various tests that were timing out
  packages/dashboard-hardhat-plugin/test/hardhat.test.ts
  packages/debugger/test/step.js
Labels: internal improvement

#6056 Add missing sinon dev dependency
  packages/fetch-and-compile/package.json
Labels: internal improvement

#6060 Add two more sourcify networks
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#6061 Increase timeout on failing hardhat test
  packages/dashboard-hardhat-plugin/test/hardhat.test.ts
Labels: internal improvement
