Repository trufflesuite/truffle, pull requests merged in 2023-06, with the labels that each got.

#6044 Swap priority order of bools/strings if strictBooleans is on
  packages/codec/lib/wrap/index.ts
  packages/codec/lib/wrap/priority.ts
  packages/encoder/lib/encoders.ts
  packages/encoder/test/overload.test.ts
Labels: 🐜 bug fix

#6082 Reject SolidityAST contracts verified on Etherscan
  packages/source-fetcher/lib/etherscan.ts
  packages/source-fetcher/lib/types.ts
Labels: internal improvement

#6083 Put try/catch guard around ENS forward resolution in decoder/debugger
  packages/debugger/lib/web3/adapter.js
  packages/decoder/lib/decoders.ts
Labels: 🐜 bug fix

#6089 Add chains for Sourcify 2.2.3
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#6090 Replace bootstrap with install in scripts/workflows
  .github/workflows/nodejs.yml
  scripts/prepare-release.sh
Labels: internal improvement

#6091 Further increase timeouts on hardhat related tests
  packages/dashboard-hardhat-plugin/test/hardhat.test.ts
Labels: internal improvement

#6092 Increase timeout on some more tests, remove needless imports
  packages/core/test/lib/mnemonics/mnemonic.js
  packages/debugger/test/data/calldata.js
Labels: internal improvement

#5974 Allow to override chai from the config
  packages/test/src/Test.ts
Labels: enhancement, doc-change-required, new-feature: @truffle/test

#6057 Allow decoder to use 4byte.directory to decode
  packages/codec/lib/core.ts
  packages/codec/lib/format/errors.ts
  packages/codec/lib/format/utils/inspect.ts
  packages/codec/lib/types.ts
  packages/decoder/lib/decoders.ts
  packages/decoder/lib/fetch-signatures.ts
  packages/decoder/lib/index.ts
  packages/decoder/lib/types.ts
  packages/decoder/package.json
  packages/decoder/test/current/contracts/Sink.sol
  packages/decoder/test/current/migrations/2_deploy_contracts.js
  packages/decoder/test/current/test/selector-based-test.js
Labels: enhancement, new-feature: @truffle/decoder

#6099 Remove flaky hardhat test
  packages/dashboard-hardhat-plugin/test/hardhat.test.ts
Labels: internal improvement

#6114 Remove the other slow Hardhat test
  packages/dashboard-hardhat-plugin/package.json
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incompatible/.gitignore
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incompatible/contracts/SimpleStorage.sol
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incompatible/hardhat.config.no.plugin.ts
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incompatible/hardhat.config.ts
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incorrect-version/.gitignore
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incorrect-version/contracts/SimpleStorage.sol
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incorrect-version/hardhat.config.ts
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incorrect-version/package.json
  packages/dashboard-hardhat-plugin/test/fixture-projects/hardhat-project-incorrect-version/yarn.lock
  packages/dashboard-hardhat-plugin/test/hardhat.test.ts
Labels: internal improvement

#6117 Add zora network to Sourcify fetcher
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#6120 Remove cronos testnet from etherscan fetcher
  packages/source-fetcher/lib/etherscan.ts
  packages/source-fetcher/lib/networks.ts
Labels: internal improvement

#6049 Properly handle event decoding in Solidity 0.8.20
  packages/codec/lib/abi-data/allocate/index.ts
  packages/codec/lib/abi-data/allocate/types.ts
  packages/codec/lib/ast/types.ts
  packages/codec/lib/export.ts
  packages/codec/lib/types.ts
  packages/debugger/test/helpers.js
  packages/decoder/test/current/truffle-config.js
Labels: enhancement, breaking-change: @truffle/decoder, wait to merge ⏸, breaking-change: @truffle/debugger, breaking-change: @truffle/codec

#6127 Add Rollux & its testnet to Sourcify fetcher
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#6130 Add `contractClass` interpretation to address values
  packages/codec/lib/basic/decode/index.ts
  packages/codec/lib/format/elementary.ts
  packages/codec/lib/format/utils/inspect.ts
  packages/debugger/test/data/more-decoding.js
Labels: enhancement, new-feature: @truffle/decoder, new-feature: @truffle/debugger, new-feature: @truffle/codec

#6131 Allow strings and bigints instead of numbers in decoder input fields
  packages/decoder/lib/decoders.ts
  packages/decoder/lib/types.ts
  packages/decoder/test/current/test/compatible-nativize.js
  packages/decoder/test/current/test/wire-test.js
Labels: enhancement
