Repository trufflesuite/truffle, pull requests merged in 2023-01, with the labels that each got.

#5825 Remove unused dev dependency for codec docs
  packages/codec/package.json
  yarn.lock
Labels: internal improvement

#5824 Update Ganache to 7.7.3
  packages/artifactor/package.json
  packages/contract-tests/package.json
  packages/core/package.json
  packages/db/package.json
  packages/debugger/package.json
  packages/decoder/package.json
  packages/deployer/package.json
  packages/encoder/package.json
  packages/environment/package.json
  packages/hdwallet-provider/package.json
  packages/interface-adapter/package.json
  packages/provider/package.json
  packages/truffle/package.json
  yarn.lock
Labels: dependencies

#5823 Build codec and preserve docs as part of bootstrap
  package.json
Labels: internal improvement

#5831 Update Sourcify networks for January 2023
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#5862 Update web3 to 1.8.2
  packages/abi-utils/package.json
  packages/artifactor/package.json
  packages/codec/package.json
  packages/contract-tests/package.json
  packages/contract/package.json
  packages/core/package.json
  packages/db-kit/package.json
  packages/db/package.json
  packages/debugger/package.json
  packages/decoder/package.json
  packages/deployer/package.json
  packages/encoder/package.json
  packages/environment/package.json
  packages/events/package.json
  packages/external-compile/package.json
  packages/fetch-and-compile/package.json
  packages/hdwallet-provider/package.json
  packages/interface-adapter/package.json
  packages/migrate/package.json
  packages/provider/package.json
  packages/require/package.json
  packages/resolver/package.json
  packages/source-fetcher/package.json
  packages/source-map-utils/package.json
  packages/test/package.json
  packages/truffle/package.json
  yarn.lock
Labels: dependencies
