Repository trufflesuite/truffle, pull requests merged in 2023-02, with the labels that each got.

#5864 Add appendCBOR field in metadata settings type in source fetcher
  packages/source-fetcher/lib/types.ts
Labels: internal improvement

#5865 Update highlightjs-solidity to 2.0.6
  packages/debug-utils/package.json
  yarn.lock
Labels: dependencies

#5866 Add `block.prevrandao` as globally available variable in debugger
  packages/codec/lib/compiler/types.ts
  packages/codec/lib/compiler/utils.ts
  packages/codec/lib/special/decode/index.ts
  packages/debugger/test/data/global.js
  packages/debugger/test/helpers.js
Labels: enhancement

#5846 Support switching accounts between signature requests in dashboard
  packages/dashboard/src/contexts/DashContext/DashProvider.tsx
  packages/dashboard/src/contexts/DashContext/state.ts
  packages/dashboard/src/contexts/DashContext/types/Action.ts
Labels: dashboard

#5861 Properly handle quotes, backslashes, etc in commands at console
  packages/core/lib/command-utils.js
  packages/core/lib/console-child.js
  packages/core/lib/console.js
  packages/core/test/lib/command-utils.js
Labels: 🐜 bug fix

#5872 Prevent spawned Hardhat console from triggering a compile
  packages/from-hardhat/src/ask-hardhat.ts
Labels: breaking-change: @truffle/from-hardhat

#5884 Bump tsd dev dependency to ^0.25.0
  packages/expect/package.json
  yarn.lock
Labels: dependencies

#5904 Update Sourcify chains for February 2023
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#5903 Fix (most) incorrect reports of custom errors
  packages/contract-tests/test/errors.js
  packages/contract-tests/test/sources/Example.sol
  packages/contract/lib/reason.js
Labels: 🐜 bug fix

#5898 Add support for PUSH0 instruction to debugger & disassembler
  packages/code-utils/src/index.ts
  packages/code-utils/src/opcodes.ts
  packages/codec/lib/abi-data/allocate/index.ts
  packages/codec/lib/contexts/utils.ts
  packages/core/lib/commands/opcode/run.js
  packages/debug-utils/index.js
Labels: enhancement

#5906 Update ganache to 7.7.5
  packages/artifactor/package.json
  packages/contract-tests/package.json
  packages/core/package.json
  packages/db/package.json
  packages/debugger/package.json
  packages/decoder/package.json
  packages/deployer/package.json
  packages/encoder/package.json
  packages/environment/package.json
  packages/hdwallet-provider/package.json
  packages/interface-adapter/package.json
  packages/provider/package.json
  packages/truffle/package.json
  yarn.lock
Labels: dependencies

#5907 Increase timeout on migration out of gas test
  packages/truffle/test/scenarios/migrations/errors.js
Labels: internal improvement

#5909 Update Sourcify networks for Sourcify 1.2.2
  packages/source-fetcher/lib/networks.ts
  packages/source-fetcher/lib/sourcify.ts
Labels: enhancement

#5912 Remove Aurora support from Etherscan fetcher
  packages/source-fetcher/lib/etherscan.ts
Labels: internal improvement

#5938 Stop serializing HH config data we don't need
  packages/from-hardhat/src/api.ts
Labels: 🐜 bug fix
